version: "3.9"
services:
  db:
    restart: on-failure
    image: postgres
    container_name: db
    hostname: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=jonas
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=jonas
  point_of_sale:
    build: .
    container_name: pos
    ports:
      - "3001:3001"
    depends_on:
      - db
    external_links:
      - db
    environment:
      - FLASK_APP=setup.py
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=jonas
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=jonas
    volumes:
      - .:/home/app